## **Numpy Array Operations**

In [ ]:
import numpy as np

In [ ]:
temperatures_w1=np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])

In [ ]:
print(temperatures_w1)

[22.5 25.3 20.8 23.4 26.1 24.8 21.9]


In [ ]:
type(temperatures_w1)

numpy.ndarray

In [ ]:
print(temperatures_w1.shape)

(7,)


In [ ]:
print(temperatures_w1.dtype)

float64


In [ ]:
print(temperatures_w1.size)

7


In [ ]:
Fahrenheit=(temperatures_w1*9/5)+32

In [ ]:
print(Fahrenheit)

[72.5  77.54 69.44 74.12 78.98 76.64 71.42]


In [ ]:
print(np.max(temperatures_w1))

26.1


In [ ]:
print(np.min(temperatures_w1))

20.8


In [ ]:
print(np.mean(temperatures_w1))

23.542857142857144


In [ ]:
print(temperatures_w1[:3])

[22.5 25.3 20.8]


In [ ]:
print(temperatures_w1[-2:])

[24.8 21.9]


In [ ]:
print(temperatures_w1[2:5])

[20.8 23.4 26.1]


# **2D** **Array**

In [ ]:
temperatures=np.array([[22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],[19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1]])


In [ ]:
print(temperatures)

[[22.5 25.3 20.8 23.4 26.1 24.8 21.9]
 [19.2 22.5 21.3 24.  23.5 22.8 20.1]]


In [ ]:
type(temperatures)

numpy.ndarray

In [ ]:
print(np.shape(temperatures))

(2, 7)


In [ ]:
print(np.size(temperatures))

14


In [ ]:
print(temperatures.dtype)

float64


In [ ]:
print(temperatures[0])

[22.5 25.3 20.8 23.4 26.1 24.8 21.9]


In [ ]:
print(temperatures[1])

[19.2 22.5 21.3 24.  23.5 22.8 20.1]


In [ ]:
print(temperatures[0][-2:])

[24.8 21.9]


In [ ]:
print(temperatures[1][-2:])

[22.8 20.1]


# **Pandas Series**

In [ ]:
import pandas as pd

In [ ]:
marks=pd.Series([95, 92, 89, 85, 80],index = ['Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5'])

In [ ]:
print(marks)

Rank1    95
Rank2    92
Rank3    89
Rank4    85
Rank5    80
dtype: int64


In [ ]:
print(marks.iloc[0])

95


In [ ]:
print(marks.loc[['Rank1','Rank2','Rank3']])

Rank1    95
Rank2    92
Rank3    89
dtype: int64


In [ ]:
print(marks.iloc[2])

89


In [ ]:
print(marks[marks>90])

Rank1    95
Rank2    92
dtype: int64


In [ ]:
marks["Rank1"]=100

In [ ]:
print(marks)

Rank1    100
Rank2     92
Rank3     89
Rank4     85
Rank5     80
dtype: int64


In [ ]:
marks=(marks.drop('Rank5'))

In [ ]:
print(marks)

Rank1    100
Rank2     92
Rank3     89
Rank4     85
dtype: int64


In [ ]:
CGPA=marks/10

In [ ]:
print(CGPA)

Rank1    10.0
Rank2     9.2
Rank3     8.9
Rank4     8.5
dtype: float64


# **Pandas DataFrame**


In [ ]:
data={
    'TransactionID': [101,102,103,104,105,106,107,108,109,110],
    'ProductCategory': ['Electronics','Clothing','Electronics','Furniture','Clothing',
                        'Electronics','Furniture','Clothing','Furniture','Electronics'],
    'Region': ['North','South','North','East','West','North','East','West','South','North'],
    'Amount': [200,150,300,450,200,250,300,180,350,400]
}


In [ ]:
print(data)

{'TransactionID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110], 'ProductCategory': ['Electronics', 'Clothing', 'Electronics', 'Furniture', 'Clothing', 'Electronics', 'Furniture', 'Clothing', 'Furniture', 'Electronics'], 'Region': ['North', 'South', 'North', 'East', 'West', 'North', 'East', 'West', 'South', 'North'], 'Amount': [200, 150, 300, 450, 200, 250, 300, 180, 350, 400]}


In [ ]:
transactions=pd.DataFrame(data)

In [ ]:
print(transactions)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400


In [ ]:
print(transactions.head)

<bound method NDFrame.head of    TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400>


In [ ]:
print(transactions.tail)

<bound method NDFrame.tail of    TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400>


In [ ]:
print(transactions.shape)

(10, 4)


In [ ]:
print(transactions.columns)

Index(['TransactionID', 'ProductCategory', 'Region', 'Amount'], dtype='object')


In [ ]:
print(transactions.dtypes)

TransactionID       int64
ProductCategory    object
Region             object
Amount              int64
dtype: object


In [ ]:
print(transactions[['ProductCategory','Amount']])

  ProductCategory  Amount
0     Electronics     200
1        Clothing     150
2     Electronics     300
3       Furniture     450
4        Clothing     200
5     Electronics     250
6       Furniture     300
7        Clothing     180
8       Furniture     350
9     Electronics     400


In [ ]:
print(transactions.iloc[:,-3:])

  ProductCategory Region  Amount
0     Electronics  North     200
1        Clothing  South     150
2     Electronics  North     300
3       Furniture   East     450
4        Clothing   West     200
5     Electronics  North     250
6       Furniture   East     300
7        Clothing   West     180
8       Furniture  South     350
9     Electronics  North     400


In [ ]:
filtered = transactions[
    (transactions['Region'] == 'North') &
    (transactions['Amount'] > 200)
]

print(filtered)

   TransactionID ProductCategory Region  Amount
2            103     Electronics  North     300
5            106     Electronics  North     250
9            110     Electronics  North     400


In [ ]:
print(transactions['ProductCategory'].value_counts())

ProductCategory
Electronics    4
Clothing       3
Furniture      3
Name: count, dtype: int64


In [ ]:
print(transactions['Region'].unique())

['North' 'South' 'East' 'West']


In [ ]:
print(transactions.groupby('Region')['Amount'].mean())

Region
East     375.0
North    287.5
South    250.0
West     190.0
Name: Amount, dtype: float64


In [ ]:
transactions.loc[transactions['TransactionID']==102,'Amount']=165
print(transactions)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400


In [ ]:
transactions['Discount']=transactions['Amount']*0.10

In [ ]:
print(transactions)

   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
8            109       Furniture  South     350      35.0
9            110     Electronics  North     400      40.0


In [ ]:
transactions=transactions[transactions['TransactionID']!=109]

In [ ]:
print(transactions)

   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
9            110     Electronics  North     400      40.0


In [ ]:
transactions=transactions.drop(columns=('Discount'))

In [ ]:
print(transactions)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
9            110     Electronics  North     400
